### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by zhiqiang21** [vladimir-tikhonov/tree-view-copy-relative-path#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [tree-view-copy-relative-path](https://github.com/vladimir-tikhonov/tree-view-copy-relative-path) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/zhiqiang/.atom/packages/tree-view-copy-relative-path/lib/tree-view-copy-relative-path.coffee:36

TypeError: Cannot read property 'file' of undefined
    at Object.module.exports.TreeViewCopyRelativePath.copyRelativePath (/Users/zhiqiang/.atom/packages/tree-view-copy-relative-path/lib/tree-view-copy-relative-path.coffee:36:5)
    at tree-view-file.<anonymous> (/Users/zhiqiang/.atom/packages/tree-view-copy-relative-path/lib/tree-view-copy-relative-path.coffee:25:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:172:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:03.7.0 tree-view-copy-relative-path:copy-path (span.name.icon.icon-file-media)
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "atom-minify"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.20
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.28.26
atom-minify, v0.7.1
atom-ternjs, v0.13.2
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
autocomplete-sass, v0.1.0
color-picker, v2.1.1
copy-filename, v1.0.1
docblockr, v0.7.3
emmet, v2.4.3
expand-selection-to-quotes, v0.7.0
file-icons, v1.6.18
highlight-column, v0.5.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
language-jade, v0.6.3
language-vue, v0.9.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.1.3
linter-htmlhint, v1.1.0
linter-pylint, v1.2.0
markdown-scroll-sync, v2.1.2
markdown-table-formatter, v2.8.0
markdown-writer, v2.3.2
minimap, v4.21.0
pigments, v0.24.5
project-manager, v2.7.6
react, v0.14.2
run-in-browser, v0.1.3
sync-settings, v0.7.2
tree-view-copy-relative-path, v1.0.0
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by vladimir-tikhonov** [comment]
Hi, @zhiqiang21. Could you please provide steps to reproduce?

**Comment by zhiqiang21** [comment]
@vladimir-tikhonov i'm sorry for this question.it happen that I first used . then unload it.    just now i install again ,try to find it , but  the problem  not happen !

**Comment by vladimir-tikhonov** [comment]
@zhiqiang21 it's ok, just let me know if it happens again :)

**Comment by zhiqiang21** [comment]
@vladimir-tikhonov OK！
