### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of undefined

### ISSUE THREAD

**Issue by ace-bouk** [vladimir-tikhonov/tree-view-copy-relative-path#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu Zesty
**Thrown From**: [tree-view-copy-relative-path](https://github.com/vladimir-tikhonov/tree-view-copy-relative-path) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dataset' of undefined

```
At /home/elliot/.atom/packages/tree-view-copy-relative-path/lib/tree-view-copy-relative-path.coffee:8

TypeError: Cannot read property 'dataset' of undefined
    at extractPath (/packages/tree-view-copy-relative-path/lib/tree-view-copy-relative-path.coffee:8:24)
    at /packages/tree-view-copy-relative-path/lib/tree-view-copy-relative-path.coffee:30:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:24 core:cancel (input.hidden-input)
     -3:20.9.0 tree-view-copy-relative-path:copy-path (linter-decoration.linter-warning)
     -3:19.7.0 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:15.9.0 tree-view-copy-relative-path:copy-path (linter-decoration.linter-warning)
     -3:11.1.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.file-colors)
     -3:04.3.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -3:03.6.0 intentions:highlight (input.hidden-input)
     -3:02.5.0 core:paste (input.hidden-input)
     -2:55.6.0 tree-view-copy-relative-path:copy-path (linter-decoration.linter-warning)
     -2:50.6.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:48.2.0 intentions:highlight (input.hidden-input)
     -2:47.6.0 settings-view:open (input.hidden-input)
     -2:35.7.0 core:confirm (input.hidden-input)
     -2:25 editor:consolidate-selections (input.hidden-input)
     -2:25 core:cancel (input.hidden-input)
     -0:06.2.0 tree-view-copy-relative-path:copy-path (linter-decoration.linter-warning)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bugs 0.24.0 
atom-ctags 5.0.0 
atom-jade 0.3.0 
atom-nodejs-snippets 1.5.0 
atom-ternjs 0.18.2 
auto-detect-indentation 1.3.0 
autocompiler-pug-jade 2.0.1 
autocomplete-modules 1.6.8 
busy-signal 1.3.0 
docblockr 0.9.3 
editorconfig 2.2.2 
emmet 2.4.3 
es6-snippets 0.3.0 
file-icons 2.1.1 
filecolor 0.4.0 
floobits 0.32.10 
fuzzy-finder-plus 1.4.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
jade-beautify 0.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.10.1 
language-babel 2.57.1 
language-javascript-jsx 0.3.7 
language-pug 0.0.21 
linter 2.1.2 
linter-csslint 1.3.4 
linter-eslint 8.1.4 
linter-gcc 0.7.1 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-pug 1.3.1 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-stylelint 3.9.0 
linter-tidy 2.3.1 
linter-ui-default 1.2.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
one-dark-vivid-syntax 1.7.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.1 
react-es6-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
reason 0.0.0 
recent-files-fuzzy-finder 0.3.1 
redux-snippets 0.2.2 
selection-highlight 0.1.6 
tree-view-copy-relative-path 1.1.0 
uglify 1.3.1 
```

**Comment by andreieftimie** [comment]
I'm also seeing this.
